In [6]:
import roslib
import rospy

from pykdl_utils.kdl_parser import kdl_tree_from_urdf_model
from pykdl_utils.kdl_kinematics import KDLKinematics
from urdf_parser_py.urdf import URDF

In [2]:
robot = URDF.from_parameter_server()
print(robot)

gazebos: ["<gazebo xmlns:xacro=\"http://www.ros.org/wiki/xacro\" reference=\"bottom_link\"\
    >\n    <material>Gazebo/White</material>\n  </gazebo>\n  \n", "<gazebo xmlns:xacro=\"\
    http://www.ros.org/wiki/xacro\" reference=\"base_link\">\n    <material>Gazebo/White</material>\n\
    \  </gazebo>\n  \n", "<gazebo xmlns:xacro=\"http://www.ros.org/wiki/xacro\" reference=\"\
    link_1\">\n    <material>Gazebo/Red</material>\n  </gazebo>\n  \n", "<gazebo xmlns:xacro=\"\
    http://www.ros.org/wiki/xacro\" reference=\"link_2\">\n    <material>Gazebo/White</material>\n\
    \  </gazebo>\n  \n", "<gazebo xmlns:xacro=\"http://www.ros.org/wiki/xacro\" reference=\"\
    link_3\">\n    <material>Gazebo/Black</material>\n  </gazebo>\n  \n", "<gazebo\
    \ xmlns:xacro=\"http://www.ros.org/wiki/xacro\" reference=\"link_4\">\n    <material>Gazebo/Red</material>\n\
    \  </gazebo>\n  \n", "<gazebo xmlns:xacro=\"http://www.ros.org/wiki/xacro\" reference=\"\
    link_5\">\n    <material>Gazebo/B

Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface


In [3]:
tree = kdl_tree_from_urdf_model(robot)
print tree.getNrOfSegments()

6


In [4]:
base_link = 'base_link'
end_link = 'link_5'
chain = tree.getChain(base_link, end_link)
print chain.getNrOfJoints()

5


In [7]:
kdl_kin = KDLKinematics(robot, base_link, end_link)

In [8]:
q = kdl_kin.random_joint_angles()
print q

[ 0.71718003  1.28968236 -1.69017389  3.82286286 -2.07920242]


In [9]:
pose = kdl_kin.forward(q)

In [10]:
q_ik = kdl_kin.inverse(pose, q+0.3) # inverse kinematics
if q_ik is not None:
    pose_sol = kdl_kin.forward(q_ik) # should equal pose
J = kdl_kin.jacobian(q)
print 'q:', q
print 'q_ik:', q_ik
print 'pose:', pose
if q_ik is not None:
    print 'pose_sol:', pose_sol
print 'J:', J

q: [ 0.71718003  1.28968236 -1.69017389  3.82286286 -2.07920242]
q_ik: [ 0.71718003  1.28968236 -1.69017389  3.82286282 -2.07920248]
pose: [[ 0.01505506  0.8711731   0.49074513 -0.27645404]
 [-0.75788787  0.33008436 -0.56271689  0.31700102]
 [-0.6522111  -0.36345804  0.66522096  0.19364239]
 [ 0.          0.          0.          1.        ]]
pose_sol: [[ 0.01505503  0.87117311  0.49074511 -0.27645404]
 [-0.75788791  0.33008431 -0.56271686  0.31700102]
 [-0.65221106 -0.36345806  0.665221    0.19364239]
 [ 0.          0.          0.          1.        ]]
J: [[ -3.17001020e-01   1.74932886e-01  -2.43300058e-01   0.00000000e+00
    0.00000000e+00]
 [ -2.76454041e-01  -2.00591029e-01   2.78983340e-01   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00  -4.20614411e-01   6.03976991e-02   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00  -7.53662179e-01   7.53660504e-01   7.53660504e-01
    4.90745126e-01]
 [  0.00000000e+00  -6.57261987e-01   6.57263908e-01   6.57263908e-01
   -5.62

/home/anudeep/catkin_ws/src/hrl-kdl/pykdl_utils/src/pykdl_utils/kdl_kinematics.py:249: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if np.any(q_guess == None):
